Changed datadir from array
Apparently as of puppet 3.2 the data dir value can't be an array.. youch

Error: Error from DataBinding 'hiera' while looking up
'common::proxy_port': datadir for yaml cannot be an array on node
logus.law.harvard.edu
Wrapped exception:
datadir for yaml cannot be an array
Wrapped exception:
datadir for yaml cannot be an array
Error: Error from DataBinding 'hiera' while looking up
'common::proxy_port': datadir for yaml cannot be an array on node
logus.law.harvard.edu